### ISSUE TITLE
회원가입 정보 등록

### ISSUE THREAD

**Issue by wdhv2007** [damdev-study/blog-api#10]
id, userId, userName, password, regDate, modifyDate, status

**Comment by wdhv2007** [comment]
auth 추가

**Comment by wdhv2007** [comment]
status code
미인증 : unauth
인증 : auth
휴면 : dormant
탈퇴 : out

**Comment by wdhv2007** [comment]
roll code
관리자 : admin
일반사용자 : user

**Comment by zenic88** [comment]
User 클래스 이름 변경 필요
시큐리티에서 사용할 클래스랑 이름 겹침
